export const SAVE_POSTS = 'SAVE_POSTS'
export const ITEM_CLICKED = 'ITEM_CLICKED'
export const ITEM_SELECTED = 'ITEM_SELECTED'
export const ITEM_DISMISSED = 'ITEM_DISMISSED'
export const CLEAR_POSTS = 'CLEAR_POSTS'

